pub fn print_notices() {
    print!(
        "{}",
        concat!(
            include_str!("../assets/NOTICE.txt"),
            "\nUpstream code projects:\n",
            include_str!("../assets/licenses/code-projects.txt"),
            "\n",
            include_str!("../LICENSE"),
            "\n",
            include_str!("../assets/licenses/cc0.txt"),
            "\n",
            include_str!("../assets/licenses/rodio-mit.txt"),
            "\n",
            include_str!("../assets/licenses/apache-2.0.txt"),
            "\n",
            include_str!("../assets/licenses/anyhow.txt"),
            "\n",
            include_str!("../assets/licenses/pi-yappi-themes.txt"),
            "\n",
            include_str!("../assets/licenses/pi-yappi-themes-notice.md"),
            "\nTree-sitter runtime, highlighter and language bindings:\n",
            include_str!("../assets/licenses/tree-sitter.txt"),
            "\nTree-sitter Rust grammar:\n",
            include_str!("../assets/licenses/tree-sitter-rust.txt"),
            "\nTree-sitter Python grammar:\n",
            include_str!("../assets/licenses/tree-sitter-python.txt"),
            "\nTree-sitter JavaScript grammar:\n",
            include_str!("../assets/licenses/tree-sitter-javascript.txt"),
            "\nTree-sitter TypeScript grammar:\n",
            include_str!("../assets/licenses/tree-sitter-typescript.txt"),
            "\nTree-sitter Go grammar:\n",
            include_str!("../assets/licenses/tree-sitter-go.txt"),
            "\nTree-sitter GDScript grammar:\n",
            include_str!("../assets/licenses/tree-sitter-gdscript.txt"),
            "\nregex, regex-automata and regex-syntax:\n",
            include_str!("../assets/licenses/regex-mit.txt"),
            "\naho-corasick:\n",
            include_str!("../assets/licenses/aho-corasick-mit.txt"),
            "\nstreaming-iterator:\n",
            include_str!("../assets/licenses/streaming-iterator-mit.txt"),
            "\nthiserror and thiserror-impl:\n",
            include_str!("../assets/licenses/thiserror-mit.txt"),
            "\ntiny-skia:\n",
            include_str!("../assets/licenses/tiny-skia-0.12.0.txt"),
            "\ntiny-skia-path:\n",
            include_str!("../assets/licenses/tiny-skia-path-0.12.0.txt"),
            "\narrayref:\n",
            include_str!("../assets/licenses/arrayref-0.3.9.txt"),
            "\narrayvec:\n",
            include_str!("../assets/licenses/arrayvec-0.7.8.txt"),
            "\nbytemuck:\n",
            include_str!("../assets/licenses/bytemuck-1.25.2.txt"),
            "\nstrict-num:\n",
            include_str!("../assets/licenses/strict-num-0.1.1.txt"),
            "\nJetBrains Mono:\n",
            include_str!("../assets/licenses/jetbrains-mono-ofl.txt"),
            "\nfontdue:\n",
            include_str!("../assets/licenses/fontdue-0.9.4.txt"),
            "\nttf-parser:\n",
            include_str!("../assets/licenses/ttf-parser-0.25.1.txt"),
            "\ncore_maths:\n",
            include_str!("../assets/licenses/core_maths-0.1.1.txt"),
            "\nlibm:\n",
            include_str!("../assets/licenses/libm-0.2.16.txt"),
        )
    );
}
